spring:
  application:
    name: session-service

  datasource:
    url: jdbc:mysql://localhost:3306/ZomatoMicroservice
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
      format_sql: true
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: noreplyonthisemail7@gmail.com
    password: sqknotbfvhlhsyda
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true

server:
  port: 9797

customerService:
  url: http://CUSTOMER-SERVICE/api/customers

restaurantService:
  url: http://RESTAURANT-SERVICE/api/restaurants
