spring:
  application:
    name: Z-Session

  datasource:
    url: jdbc:mysql://localhost:3306/zomatomicroservice
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    prefer-ip-address: true

# Custom service URLs
customerService:
  url: http://localhost:6969/api/customers

restaurantService:
  url: http://localhost:9696/api/restaurants

server:
  port: 9797
