spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: session-service
          uri: lb://SESSION-SERVICE
          predicates:
            - Path=/api/public/session/**

server:
  port: 8989

# Eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true

