server:
  port: 8080

spring:
  application:
    name: Z-Gateway
  main:
    web-application-type: reactive


eureka:
  client:
    register-with-eureka: false   # Eureka Server doesn't register itself
    fetch-registry: false         # No need to fetch registry for server

spring.cloud.gateway.routes:
  - id: session-service
    uri: lb://Z-Session
    predicates:
      - Path=/api/public/session/**

  - id: customer-service
    uri: lb://Z-Customer
    predicates:
      - Path=/api/customers/**

  - id: restaurant-service
    uri: lb://Z-Restaurant
    predicates:
      - Path=/api/restaurants/**

