spring:
  application:
    name: Z-Restaurant

  datasource:
    url: jdbc:mysql://localhost:3306/ZomatoMicroservice
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        "[format_sql]": true
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: noreplyonthisemail7@gmail.com
    password: sqknotbfvhlhsyda
    properties:
      "[mail.smtp.auth]": true
      "[mail.smtp.starttls.enable]": true
      "[mail.smtp.starttls.required]": true

  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 9696

# Logging configuration
logging:
  level:
    "[org.springframework.security]": DEBUG
